USE BD_PLPII;
/*Archivo sql de Alvaro*/

DROP PROCEDURE IF EXISTS usp_ProyectosDirigidos;
DROP PROCEDURE IF EXISTS usp_ProyectosDireccion;
DROP PROCEDURE IF EXISTS usp_ProyectosParticipas;
DROP PROCEDURE IF EXISTS usp_ProyectosParticipados;

/*PROYECTOS DIRIGIDOS*/ /*P_COD_TRABAJADOR	CHAR(5)*/
delimiter $$
CREATE PROCEDURE usp_ProyectosDirigidos(P_COD_TRABAJADOR	CHAR(5))
BEGIN
SELECT P.NUM_PROYECTO, FECHA_REG_PROYECTO, FECHA_ACT_PROYECTO, DEPARTAMENTO_PROYECTO, PROVINCIA_PROYECTO, 
DISTRITO_PROYECTO, DIRECCION_PROYECTO, ETAPA_PROYECTO, COSTO_PROYECTO, MONTO_TOTAL_PROYECTO, 
CAN_MES_TRABAJO, NUM_SOLICITUD
FROM PROYECTO P INNER JOIN DETALLE_PROYECTO DP
ON P.NUM_PROYECTO = DP.NUM_PROYECTO
WHERE DP.COD_TRABAJADOR = P_COD_TRABAJADOR AND ETAPA_PROYECTO = 'CUARTA';
end $$
delimiter ;

call usp_ProyectosDirigidos('T1010');

select * from PROYECTO;

/*PROYECTOS EN DIRECCIÓN*/
delimiter $$
CREATE PROCEDURE usp_ProyectosDireccion(P_COD_TRABAJADOR	CHAR(5))
BEGIN
SELECT P.NUM_PROYECTO, FECHA_REG_PROYECTO, FECHA_ACT_PROYECTO, DEPARTAMENTO_PROYECTO, PROVINCIA_PROYECTO, 
DISTRITO_PROYECTO, DIRECCION_PROYECTO, ETAPA_PROYECTO, COSTO_PROYECTO, MONTO_TOTAL_PROYECTO, 
CAN_MES_TRABAJO, NUM_SOLICITUD 
FROM PROYECTO P INNER JOIN DETALLE_PROYECTO DP
ON P.NUM_PROYECTO = DP.NUM_PROYECTO
WHERE DP.COD_TRABAJADOR = P_COD_TRABAJADOR AND ETAPA_PROYECTO = 'PRIMERA' 
OR ETAPA_PROYECTO = 'SEGUNDA' OR ETAPA_PROYECTO = 'TERCERA';
end $$
delimiter ;

call usp_ProyectosDireccion('T1010');

/*PROYECTOS EN LOS QUE PARTICIPAS*/
delimiter $$
CREATE PROCEDURE usp_ProyectosParticipas(P_COD_TRABAJADOR	CHAR(5))
BEGIN
SELECT P.NUM_PROYECTO, FECHA_REG_PROYECTO, FECHA_ACT_PROYECTO, DEPARTAMENTO_PROYECTO, PROVINCIA_PROYECTO, 
DISTRITO_PROYECTO, DIRECCION_PROYECTO, ETAPA_PROYECTO, COSTO_PROYECTO, MONTO_TOTAL_PROYECTO, 
CAN_MES_TRABAJO, NUM_SOLICITUD, SUELDO_MES, SUELDO_TOTAL 
FROM PROYECTO P INNER JOIN DETALLE_PROYECTO DP
ON P.NUM_PROYECTO = DP.NUM_PROYECTO
WHERE DP.COD_TRABAJADOR = P_COD_TRABAJADOR AND P.ETAPA_PROYECTO = 'PRIMERA' 
OR ETAPA_PROYECTO = 'SEGUNDA' OR ETAPA_PROYECTO = 'TERCERA';
end $$
delimiter ;

call usp_ProyectosParticipas('T1010');

/*PROYECTOS PARTICIPADOS*/
delimiter $$
CREATE PROCEDURE usp_ProyectosParticipados(P_COD_TRABAJADOR	CHAR(5))
BEGIN
SELECT P.NUM_PROYECTO, FECHA_REG_PROYECTO, FECHA_ACT_PROYECTO, DEPARTAMENTO_PROYECTO, PROVINCIA_PROYECTO, 
DISTRITO_PROYECTO, DIRECCION_PROYECTO, ETAPA_PROYECTO, COSTO_PROYECTO, MONTO_TOTAL_PROYECTO, 
CAN_MES_TRABAJO, NUM_SOLICITUD, SUELDO_MES, SUELDO_TOTAL 
FROM PROYECTO P INNER JOIN DETALLE_PROYECTO DP
ON P.NUM_PROYECTO = DP.NUM_PROYECTO
WHERE DP.COD_TRABAJADOR = P_COD_TRABAJADOR AND ETAPA_PROYECTO = 'CUARTA';
end $$
delimiter ;

call usp_ProyectosParticipados('T1010');