DROP DATABASE IF EXISTS BD_PLPII;
CREATE DATABASE BD_PLPII;
USE BD_PLPII;

CREATE TABLE TIPO_TRABAJO(
	COD_TIPTRABAJO			CHAR(5) 	NOT NULL PRIMARY KEY,
    DES_TIPTRABAJO			VARCHAR(50) NOT NULL,
    FECHA_REG_TIPOTRABAJO	VARCHAR(10)	NOT NULL,
    ESTADO_TIPTRABAJO		VARCHAR(9)	NOT NULL
)
;

CREATE TABLE TRABAJADOR(
	COD_TRABAJADOR			CHAR(5)		NOT NULL PRIMARY KEY,
    NOM_TRABAJADOR			VARCHAR(20)	NOT NULL,
    APEP_TRABAJADOR			VARCHAR(20)	NOT NULL,
    APEM_TRABAJADOR			VARCHAR(20)	NOT NULL,
    DNI_TRABAJADOR			VARCHAR(8)	NOT NULL,
    EMAIL_TRABAJADOR		VARCHAR(30)	NOT NULL,
    TELEFONO_TRABAJADOR		VARCHAR(9)	NOT NULL,
    DEPARTAMENTO_TRABAJADOR	VARCHAR(20)	NOT NULL,
    PROVINCIA_TRABAJADOR	VARCHAR(20)	NOT NULL,
    DISTRITO_TRABAJADOR		VARCHAR(20)	NOT NULL,
    DIRECCION_TRABAJADOR	VARCHAR(50)	NOT NULL,
    PASS_TRABAJADOR			VARCHAR(15)	NOT NULL,
    TIPO_TRABAJADOR			VARCHAR(20)	NOT NULL,
    FECHA_REG_TRABAJADOR	VARCHAR(10)	NOT NULL,
    ESTADO_TRABAJADOR		VARCHAR(9)	NOT NULL
);

CREATE TABLE CLIENTE(
	COD_CLIENTE				CHAR(5)		NOT NULL PRIMARY KEY,		
    RAZSOC_CLIENTE			VARCHAR(20)	NOT NULL,
    RUC_CLIENTE				VARCHAR(11)	NOT NULL,
    EMAIL_CLIENTE			VARCHAR(30)	NOT NULL,
    TELEFONO_CLIENTE		VARCHAR(9)	NOT NULL,
    DEPARTAMENTO_CLIENTE	VARCHAR(20)	NOT NULL,
    PROVINCIA_CLIENTE		VARCHAR(20)	NOT NULL,
    DISTRITO_CLIENTE		VARCHAR(20)	NOT NULL,
    DIRECCION_CLIENTE		VARCHAR(20)	NOT NULL,
    TIPO_CLIENTE			VARCHAR(20)	NOT NULL,
    REPRESENTANTE_CLIENTE	VARCHAR(20)	NOT NULL,
    FECHA_REG_CLIENTE		VARCHAR(10)	NOT NULL,
    ESTADO_CLIENTE			VARCHAR(9)	NOT NULL    
)
;

CREATE TABLE SOLICITUD(
	NUM_SOLICITUD		CHAR(8) 	NOT NULL PRIMARY KEY,
    PERMISOS_SOLICITUD	VARCHAR(20)	NOT NULL,
    ESTADO_SOLICITUD	VARCHAR(10)	NOT NULL,
    FECHA_REG_SOLICITUD	VARCHAR(10)	NOT NULL,
    FECHA_ACT_SOLICITUD	VARCHAR(10)	NOT NULL,
    COD_CLIENTE			CHAR(5)		NOT NULL,
    FOREIGN KEY	(COD_CLIENTE)		REFERENCES	CLIENTE(COD_CLIENTE)
)
;

CREATE TABLE PROYECTO(
	NUM_PROYECTO			CHAR(8)			NOT NULL PRIMARY KEY,
    FECHA_REG_PROYECTO		VARCHAR(10)		NOT NULL,
    FECHA_ACT_PROYECTO		VARCHAR(10)		NOT NULL,
    DEPARTAMENTO_PROYECTO	VARCHAR(20)		NOT NULL,
    PROVINCIA_PROYECTO		VARCHAR(20)		NOT NULL,
    DISTRITO_PROYECTO		VARCHAR(20)		NOT NULL,
    DIRECCION_PROYECTO		VARCHAR(50)		NOT NULL,
    ETAPA_PROYECTO			VARCHAR(7)		NOT NULL,
    COSTO_PROYECTO			DECIMAL(10,2)	NOT NULL,
    CAN_MES_TRABAJO			INT				NOT NULL,
    NUM_SOLICITUD			CHAR(8)			NOT NULL,
    COD_TIPTRABAJO			CHAR(5)			NOT NULL,
    FOREIGN KEY	(COD_TIPTRABAJO)	REFERENCES	TIPO_TRABAJO(COD_TIPTRABAJO),
    FOREIGN KEY	(NUM_SOLICITUD)		REFERENCES	SOLICITUD(NUM_SOLICITUD)
)
;

CREATE TABLE DETALLE_PROYECTO(
	NUM_PROYECTO	CHAR(8)			NOT NULL,
    COD_TRABAJADOR	CHAR(5)			NOT NULL,
    SUELDO_MES		DECIMAL(10,2)	NOT NULL,
    SUELDO_TOTAL	DECIMAL(10,2)	NOT NULL,
    FOREIGN KEY (NUM_PROYECTO)		REFERENCES	PROYECTO(NUM_PROYECTO),
    FOREIGN KEY	(COD_TRABAJADOR)	REFERENCES	TRABAJADOR(COD_TRABAJADOR)
)
;


insert into TIPO_TRABAJO values('W1000', 'Excavaciones para delimitar', '18-06-2017','ACTIVO');
insert into TIPO_TRABAJO values('W1001', 'Excavaciones para medir potencia', '18-06-2017','ACTIVO');
insert into TIPO_TRABAJO values('W1002', 'Excavaciones de rescate', '18-06-2017','ACTIVO');
insert into TIPO_TRABAJO values('W1003', 'Prospecciones Arqueológicas', '18-06-2017', 'ACTIVO');
insert into TIPO_TRABAJO values('W1004', 'Monitoreo Arqueológico', '18-06-2017','ACTIVO');
insert into TIPO_TRABAJO values('W1005', 'Tramite de CIRA', '18-06-2017','ACTIVO');
insert into TIPO_TRABAJO values('W1006', 'Proyectos de puesta en valor', '18-06-2017', 'ACTIVO');