USE BD_PLPII;
/*Archivo sql de Renato*/


/*ListaProyectosParticipadosObrero*/
delimiter $$
create procedure usp_ListarParticipado(CODT CHAR(5))
begin
	SELECT P.NUM_PROYECTO, P.DEPARTAMENTO_PROYECTO, P.PROVINCIA_PROYECTO, P.DISTRITO_PROYECTO, P.DIRECCION_PROYECTO, P.FECHA_REG_PROYECTO, P.FECHA_ACT_PROYECTO, P.ETAPA_PROYECTO FROM PROYECTO P INNER JOIN DETALLE_PROYECTO DP
	ON P.NUM_PROYECTO = DP.NUM_PROYECTO
	WHERE DP.COD_TRABAJADOR = CODT AND P.ETAPA_PROYECTO = 'CUARTA';
end $$
delimiter ;

/*ListaProyectosParticipasObrero*/
delimiter $$
create procedure usp_ListarParticipas(CODT CHAR(5))
begin
	SELECT P.NUM_PROYECTO, P.DEPARTAMENTO_PROYECTO, P.PROVINCIA_PROYECTO, P.DISTRITO_PROYECTO, P.DIRECCION_PROYECTO, P.FECHA_REG_PROYECTO, P.FECHA_ACT_PROYECTO, P.ETAPA_PROYECTO FROM PROYECTO P INNER JOIN DETALLE_PROYECTO DP
	ON P.NUM_PROYECTO = DP.NUM_PROYECTO
	WHERE DP.COD_TRABAJADOR = CODT AND P.ETAPA_PROYECTO = 'PRIMERA' OR P.ETAPA_PROYECTO = 'SEGUNDA' OR P.ETAPA_PROYECTO = 'TERCERA';
end $$
delimiter ;